### ISSUE TITLE
HW1 ready for grading!

### ISSUE THREAD

**Issue by BenjaminTillius** [BenjaminTillius/su-mt4007#1]

**Comment by Daniel-S-1** [comment]
Checklist:
- Is the homework complete, e.g. are all steps in the homework done?

Title, description and background is included.
Homework is complete and all steps in homework is done.

 Also nice work using gitignore.

**Comment by LeoLevenius** [comment]
### Godkänt.
 
Tack Benjamin för din introduktion och välkommen till kursen!
