### ISSUE TITLE
HW2 ready for grading! (Waiting for grading)

### ISSUE THREAD

**Issue by BenjaminTillius** [BenjaminTillius/su-mt4007#2]

**Comment by elliphantonator** [comment]
- Has the person answered all the questions?
Yes. 

- Is there something you really like about the report?
Nothing in particular stands out, everything is alright. 

- Is anything unclear?
No.

**Comment by bettyfranklamanuens** [comment]
## Passed

Thank you for a very nice report and interesting analysis!

### Apartment Prices

Everything looks good!

### The Swedish Election of 2018

Correct!

### Predicting Strokes

Nice diagram!
